resources:
- name: commons-git
  type: git
  source:
    branch: master
    uri: git@github.com:spring-projects/eclipse-integration-commons.git
    private_key: {{rsa_id}}
- name: docker-git
  type: git
  source:
    branch: master
    uri: git@github.com:kdvolder/sts-concourse
    paths:
    - docker/**/*
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: docker-git
    trigger: true
  - put: docker-image
    params:
      build: docker-git/concourse/docker
    get_params: 
      skip_download: true

- name: build-commons-update-site
  plan:
  - get: commons-git
    trigger: true
  - task: hello-world
    config:
      inputs:
      - name: commons-git
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ubuntu
      run:
        path: echo
        args:
        - "Hello world!"
        