resources:
- name: commons-git
  type: git
  source:
    branch: master
    uri: git@github.com:spring-projects/eclipse-integration-commons.git
    private_key: {{rsa_id}}
- name: docker-git
  type: git
  source:
    branch: master
    uri: git@github.com:kdvolder/sts-concourse
    private_key: {{rsa_id}}
    paths:
    - docker/**/*
- name: docker-image
  type: docker-image
  source:
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: kdvolder/sts3-build-env
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: docker-git
    trigger: true
  - put: docker-image
    params:
      build: docker-git/docker
- name: build-commons-update-site
  plan:
  - aggregate:
    - get: commons-git
      trigger: true
    - get: docker-image
      passed:
      - build-docker-image
      trigger: true
  - task: hello-world
    image: docker-image
    config:
      inputs:
      - name: commons-git
      platform: linux
      run:
        path: which
        args:
        - mvn
