resources:
- name: concourse-git
  type: git
  source:
    branch: master
    uri: git@github.com:kdvolder/sts-concourse
    private_key: {{rsa_id}}
    paths:
    - tasks
- name: commons-git
  type: git
  source:
    branch: master
    uri: git@github.com:spring-projects/eclipse-integration-commons.git
    private_key: {{rsa_id}}
- name: docker-git
  type: git
  source:
    branch: master
    uri: git@github.com:kdvolder/sts-concourse
    private_key: {{rsa_id}}
    paths:
    - docker
- name: docker-image
  type: docker-image
  source:
    username: {{docker_hub_username}}
    password: {{docker_hub_password}}
    repository: kdvolder/sts3-build-env
- name: s3-commons-snapshot
  type: s3
  source:
    bucket: s3-test.spring.io
    access_key_id: {{s3_accesskey}}
    secret_access_key: {{s3_secretkey}}
    regexp: sts3/commons/snapshots/org.springsource.ide.eclipse.commons.site-[^\-]*-SNAPSHOT-([0-9]+).zip
jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: docker-git
    trigger: true
  - put: docker-image
    params:
      build: docker-git/docker
- name: build-commons-update-site
  plan:
  - aggregate:
    - get: concourse-git
      trigger: true
    - get: commons-git
      trigger: true
    - get: docker-image
      passed:
      - build-docker-image
      trigger: true
  - task: build-and-test-commons
    image: docker-image
    file: concourse-git/tasks/build-and-test-commons.yml
  - put: s3-commons-snapshot
    params:
      acl: public-read
      file: output/*.zip
